[package]
name = "web-segment"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-only"
authors = ["SegmentationViolator <segmentationviolator@proton.me>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gloo-timers = "0.3.0"
reqwest = { version = "0.11.22" }
tl = "0.7.7"
wasm-bindgen = "0.2.87"
web-sys = { version = "0.3.61", features = ["Window", "Element", "Document"] }
yew = { version = "0.20.0", features = ["csr"] }
yew-router = "0.17.0"

[profile.release]
strip = true
lto = true
opt-level = 3
