[package]
name = "web-segment"
version = "0.9.0"
edition = "2021"
license = "AGPL-3.0-only"
authors = ["SegmentationViolator <segmentationviolator@proton.me>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.22" }
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
stylist = { version = "0.13.0", features = ["yew_integration"] }
wasm-bindgen = "0.2.87"
yew = { version = "0.21", features = ["csr"] }
yewdux = "0.10"
yew-hooks = "0.3.2"
yew-router = "0.18"
markdown = "1.0.0-alpha.21"

[dependencies.web-sys]
version = "0.3.61"
features = [
    "Document",
    "Element",
    "Location",
    "Window",
]

[profile.release]
strip = true
lto = true
codegen-units = 1
opt-level = 'z'
