[package]
name = "web-segment"
version = "0.8.0"
edition = "2021"
license = "AGPL-3.0-only"
authors = ["SegmentationViolator <segmentationviolator@proton.me>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gloo-timers = "0.3.0"
markdown = "1.0.0-alpha.16"
reqwest = { version = "0.11.22" }
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
uuid = { version = "1.7.0", features = ["js", "v4"] }
wasm-bindgen = "0.2.87"
yew = { version = "0.21", features = ["csr"] }
yew-router = "0.18"
yewdux = "0.10"

[dependencies.web-sys]
version = "0.3.61"
features = [
    "CanvasRenderingContext2d",
    "Document",
    "Element",
    "HtmlCanvasElement",
    "Location",
    "Window",
]

# [features]
# snowfall = []

[profile.release]
strip = true
lto = true
codegen-units = 1
opt-level = 'z'
